import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { HeroHeader } from "@/components/hero-header";
import FooterSection from "@/components/footer";

export const metadata: Metadata = {
  title: "Fangki Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`font-[Open_Sans] antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <HeroHeader />
          <div className="px-12 md:mx-24 ">
          {children}
          </div>
          <FooterSection/>
        </ThemeProvider>
      </body>
    </html>
  );
}
