export { default as Gemini } from './logos/Gemini'
export { default as Replit } from './logos/Replit'
export { default as MagicUI } from './logos/MagicUI'
export { default as VSCodium } from './logos/VSCodium'
export { default as MediaWiki } from './logos/MediaWiki'
export { default as GooglePaLM } from './logos/GooglePaLM'
